[package]
name = "rust_web_scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.21.0"
csv = "1.1.6"
mongodb = "2.8.2"
tokio = {version = "1.36.0", features = ["full"]}
serde = { version = "1.0", features = ["derive"] }
